### ISSUE TITLE
Patching error

### ISSUE THREAD

**Issue by lexesv** [g0dsCookie/teamspeak3patcher#1]
deleted

**Comment by g0dsCookie** [comment]
I think you mean TS3 server 3.0.18.8? As I can't find any newer.

Problem should be the usage of the shorthands -s/-d. Should be fixed with the latest commit.

**Comment by lexesv** [comment]
There are new versions: 3.1 beta 1 & 2
http://dl.4players.de/ts/releases/pre_releases/server/3.1.0-Beta-2/

**Comment by g0dsCookie** [comment]
There are no patches available for 3.1+. At least I don't know any.

Afaik 3.1 introduces a new accounting system. I think it will take a while until there are patches available. I will leave this issue open until there are (hopefully) better news.
